config/routes.rb
Rails.application.routes.draw do

  
  resources :csvs
  resources :xmls
  resources :schemas
  #require 'sidekiq/web'
  #mount Sidekiq::Web => '/sidekiq'

  #devise_for :admins
  resources :admins
  #resources :articles
  resources :scheduled_notifications do
    collection do
        post :broadcast
        post :tip
        post :priceupdate
        post :pop_up
      end
  end

  # devise_scope :admin do
  #   authenticated :admin do
  #     root 'yoadmin/feeds#index', as: :authenticated_root
  #   end

  #   unauthenticated do
  #     root 'devise/sessions#new', as: :unauthenticated_root
  #   end
  # end
  #mount Bhf::Engine, at: 'bhf'

  use_doorkeeper do
    controllers :applications => 'oauth/applications'
  end


  # devise_for :users  do
  #   get 'logout' => 'devise/sessions#destroy'
  # end

  #get 'admin', to: 'admin#login', as: :admin

  
  root to: "admin/articles#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  namespace :admin do
    resources :articles
    resources :users do
      collection do
        post :add_representatives
      end
    end
    resources :broadcasts
    resources :feeds
    resources :tags
    resources :tips
    resources :priceupdates
    resources :denominations
    resources :categories
    resources :pop_ups
    resources :package_rates_lists do
      collection do
        get 'update_from_vox'
        get 'update_from_nexge'
      end
    end
    root to: "feeds#index"
  end

  namespace :basic do
    resources :articles
  end

  namespace :noauth do
    resources :articles
  end

  namespace :api do
    resources :otp do
      member do
        post 'gen_otp'
      end
    end
    resources :user do
      collection do
        get 'info'
        get 'search'
        get 'receiver_search'
        get 'update_device_token'
        get 'contacts'
        get 'app_users'
        get 'contacts_with_name'
        post 'contacts_sync'
        post 'contacts_sync_with_name'
        post 'follow'
        post 'firebase_token'
        get 'followers'
        get 'followings'
        post 'vox_subscribe'
        post 'nexge_subscribe'
        post 'nexge_subscribe'
        post 'unfollow'
        post 'update_device_token'
        post 'add_balance'
        get 'payment_history'
        get 'notifications'
        get 'get_balance'
        post 'voucher_recharge'
        post 'other_user_info'
        post 'balance_transfer'
      end
      member do
        #post 'follow'
      end
    end
    resources :tags do
      collection do
        post 'get_articles'
        post 'add_tags'
        post 'remove_tags'
        get 'current_user_articles'
        #get 'filtered_articles'
      end
      member do
        post 'filtered_articles'
      end
    end
    resources :collections
    resources :categories
    resources :package_rates_lists
    resources :denominations
    resources :call_costs
    resources :pop_ups
    resources :magzines do
      collection do
        get 'search'
        #get 'filtered_articles'
      end
      member do        
        post 'follow'
        post 'unfollow'
        post 'filtered_articles'
      end
      collection do
        get 'search'
        post 'remove_magzines'
      end
    end
    
    resources :rooms do
      collection do
        post 'get_room'
      end
      member do
        post 'add_members'
        post 'remove_members'
        post 'left_group'
        post 'make_admin'
      end
    end
    resources :articles do
      member do
        post 'like'
        post 'unlike'
        #post 'follow'
        #post 'unfollow'
      end
      collection do
        get 'articles_with_pagination'
        get 'sorted'
        post 'dashboard'
      end
    end
  end

	
  #  get 'channel/room'
	# get 'channel/speak'
  # Serve websocket cable requests in-process
  #mount ActionCable.server => '/cable'
end

app/models/article.rb
class Article
  include Mongoid::Document
  include Mongoid::Timestamps
  field :title, type: String
  field :summary, type: String
  field :data, :type => Hash

  
  #mount_uploader :image, ImageUploader
  
  #validates :url, presence: true
  #validates :url, uniqueness: true

  
  

end

app/controllers/admin/articles_controller.rb
module Admin
class ArticlesController < BaseController
  before_action :set_article, only: [:show,:destroy]

  def index
    @articles = Article.all.page(params[:page]).per(8)
  end


  def show
    
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to admin_articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    def set_article
      @article = Article.where(:id => params[:id]).first
    end

end
end

app/controllers/api/articles_controller.rb
module Api
class ArticlesController < BaseApiController
  before_action :set_article, only: [:show, :update, :destroy,:like,:unlike,:follow,:unfollow]
  require 'will_paginate/array'

  def index
    @articles  = Article.all
    #@articles = Article.all.order('updated_at DESC').paginate(:page => params[:page], :per_page => params[:limit])
    respond_with json: @articles
  end

  

  
  def show
    #render json: @article
    @action = "show"
    @user = current_user
    render action: 'show',location: api_article_path(@article)
  end

  

  def create
    if params[:article][:data]!=nil
      @article = Article.new(:data=>YAML::load(params[:article][:data]))
    else
      @article = Article.new(:data=>YAML::load(request.body.read))
    end

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
   
  end


  def destroy
    @article.destroy

    head :no_content
  end

  private

    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:name,:url)
    end

end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show,:destroy]

  def index
    @articles = Article.all.page(params[:page]).per(8)
  end


  def show
    
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    def set_article
      @article = Article.where(:id => params[:id]).first
    end

end

app/controllers/basic/articles_controller.rb
module Basic
class ArticlesController < BaseController
  before_action :set_article, only: [:show, :update, :destroy,:like,:unlike,:follow,:unfollow]
  require 'will_paginate/array'

  def index
    @articles  = Article.all
    #@articles = Article.all.order('updated_at DESC').paginate(:page => params[:page], :per_page => params[:limit])
    respond_with json: @articles
  end

  

  
  def show
    #render json: @article
    # @action = "show"
    # @user = current_user
    # render action: 'show',location: api_article_path(@article)
    render :json => @article.data
  end

  

  def create
    if params[:article][:data]!=nil
      @article = Article.new(:data=>YAML::load(params[:article][:data]))
    else
      @article = Article.new(:data=>YAML::load(request.body.read))
    end

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: basic_article_path(@article) }
        #respond_with json: @article.data
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
   
  end


  def destroy
    @article.destroy

    head :no_content
  end

  private

    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:name,:url)
    end

end
end

app/controllers/noauth/articles_controller.rb
module Noauth
class ArticlesController < BaseController
  before_action :set_article, only: [:show, :update, :destroy]
  require 'will_paginate/array'

  def index
    @articles  = Article.all
    #@articles = Article.all.order('updated_at DESC').paginate(:page => params[:page], :per_page => params[:limit])
    respond_with json: @articles
  end

  

  
  def show
    #render json: @article
    # @action = "show"
    # @user = current_user
    # render action: 'show',location: api_article_path(@article)
    render :json => @article.data
  end

  

  def create
    if params[:article][:data]!=nil
      @article = Article.new(:data=>YAML::load(params[:article][:data]))
    else
      @article = Article.new(:data=>YAML::load(request.body.read))
    end

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: noauth_article_path(@article)}
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
   
  end


  def destroy
    @article.destroy

    head :no_content
  end

  private

    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title,:data)
    end

end
end

app/views/admin/articles/_form.html.erb
<%if params["action"]=="edit"%>
<%@action = 'update'%>
<%@method = 'put'%>
<%else%>
<%@action = 'create'%>
<%@method = 'post'%>
<%end%>

<%= simple_form_for @article,:url=>url_for(:action =>@action,:controller => 'yoadmin/articles'),:method=>@method do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :url %>
    <%= f.select :tag_ids, @tags, class: "form-control" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-success pull-right" %>
  </div>
<% end %>

<script type="text/javascript">
  $(function() {
    $('select').selectize({plugins: ['remove_button']});
    // $('select').selectize({});
  });
</script>

app/views/admin/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', yoadmin_article_path(@article), class: "btn btn-info" %> |
<%= link_to 'Back', yoadmin_articles_path, class: "btn btn-warning" %>

app/views/admin/articles/index.html.erb
<!-- <p id="notice"><%#= notice %></p> -->

<h1>CDEE DATA 
<%= link_to 'XML', xmls_path, class: "btn btn-success pull-right" %></h1>

<%arr = []
i=0
@articles.each do |article|
  arr[i]=i
  i=i+1
end
#arr.delete(i-1)
%>

<%for i in  arr do %>

<div class="row">
  <div class="col-sm-4" style="background-color: #4ad4ad; border-color: #333;height: 20rem;width: 40rem;">
    <div class="card">
      <div class="card-block">
        <h3 class="card-title"><%= @articles[i].title %></h3>
        <p class="card-text"><%= @articles[i].data.to_s[0...200] %></p>
        <div style="display:inline !important;"><%= link_to 'Show', admin_article_path(@articles[i]), class: "btn btn-info pull-left" ,:style=> 'display:inline !important; margin-bottom:1000;'%>
        <%= link_to 'Destroy', admin_article_path(@articles[i]), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger pull-right" ,:style=> 'display:inline !important;'%></div>
      </div>
    </div>
  </div>
  <%i=i+1%>
  <%if @articles[i]!=nil%>
  <div class="col-sm-4 col-sm-offset-1" style="background-color: #4ad4ad; border-color: #333;height: 20rem;width: 40rem;">
    <div class="card">
      <div class="card-block">
        <h3 class="card-title"><%= @articles[i].title %></h3>
        <p class="card-text"><%= @articles[i].data.to_s[0...200] %></p>
        <div style="display:inline !important;"><%= link_to 'Show', admin_article_path(@articles[i]), class: "btn btn-info pull-left",:style=> 'display:inline !important;' %>
        <%= link_to 'Destroy', admin_article_path(@articles[i]), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger pull-right" ,:style=> 'display:inline !important;'%></div>
      </div>
    </div>
  </div>
</div>
<% end %>
<br>
<%arr.delete(i)%>
<% end %>

<br>

<span class="pull-right"><%= paginate @articles %></span>

app/views/admin/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', yoadmin_articles_path, class: "btn btn-warning" %>

app/views/admin/articles/show.html.erb
<!-- <p id="notice"><%#= notice %></p> -->

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Data:</strong>
  <%= @article.data%>
</p>

<%#= link_to 'Edit', edit_yoadmin_article_path(@article), class: "btn btn-info" %> 
<%#= link_to 'Back', yoadmin_articles_path, class: "btn btn-warning" %>