config/routes.rb
Rails.application.routes.draw do

  
  resources :csvs
  resources :xmls
  resources :schemas
  #require 'sidekiq/web'
  #mount Sidekiq::Web => '/sidekiq'

  #devise_for :admins
  resources :admins
  #resources :articles
  resources :scheduled_notifications do
    collection do
        post :broadcast
        post :tip
        post :priceupdate
        post :pop_up
      end
  end

  # devise_scope :admin do
  #   authenticated :admin do
  #     root 'yoadmin/feeds#index', as: :authenticated_root
  #   end

  #   unauthenticated do
  #     root 'devise/sessions#new', as: :unauthenticated_root
  #   end
  # end
  #mount Bhf::Engine, at: 'bhf'

  use_doorkeeper do
    controllers :applications => 'oauth/applications'
  end


  # devise_for :users  do
  #   get 'logout' => 'devise/sessions#destroy'
  # end

  #get 'admin', to: 'admin#login', as: :admin

  
  root to: "admin/articles#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  namespace :admin do
    resources :articles
    resources :users do
      collection do
        post :add_representatives
      end
    end
    resources :broadcasts
    resources :feeds
    resources :tags
    resources :tips
    resources :priceupdates
    resources :denominations
    resources :categories
    resources :pop_ups
    resources :package_rates_lists do
      collection do
        get 'update_from_vox'
        get 'update_from_nexge'
      end
    end
    root to: "feeds#index"
  end

  namespace :basic do
    resources :articles
  end

  namespace :noauth do
    resources :articles
  end

  namespace :api do
    resources :otp do
      member do
        post 'gen_otp'
      end
    end
    resources :user do
      collection do
        get 'info'
        get 'search'
        get 'receiver_search'
        get 'update_device_token'
        get 'contacts'
        get 'app_users'
        get 'contacts_with_name'
        post 'contacts_sync'
        post 'contacts_sync_with_name'
        post 'follow'
        post 'firebase_token'
        get 'followers'
        get 'followings'
        post 'vox_subscribe'
        post 'nexge_subscribe'
        post 'nexge_subscribe'
        post 'unfollow'
        post 'update_device_token'
        post 'add_balance'
        get 'payment_history'
        get 'notifications'
        get 'get_balance'
        post 'voucher_recharge'
        post 'other_user_info'
        post 'balance_transfer'
      end
      member do
        #post 'follow'
      end
    end
    resources :tags do
      collection do
        post 'get_articles'
        post 'add_tags'
        post 'remove_tags'
        get 'current_user_articles'
        #get 'filtered_articles'
      end
      member do
        post 'filtered_articles'
      end
    end
    resources :collections
    resources :categories
    resources :package_rates_lists
    resources :denominations
    resources :call_costs
    resources :pop_ups
    resources :magzines do
      collection do
        get 'search'
        #get 'filtered_articles'
      end
      member do        
        post 'follow'
        post 'unfollow'
        post 'filtered_articles'
      end
      collection do
        get 'search'
        post 'remove_magzines'
      end
    end
    
    resources :rooms do
      collection do
        post 'get_room'
      end
      member do
        post 'add_members'
        post 'remove_members'
        post 'left_group'
        post 'make_admin'
      end
    end
    resources :articles do
      member do
        post 'like'
        post 'unlike'
        #post 'follow'
        #post 'unfollow'
      end
      collection do
        get 'articles_with_pagination'
        get 'sorted'
        post 'dashboard'
      end
    end
  end

	
  #  get 'channel/room'
	# get 'channel/speak'
  # Serve websocket cable requests in-process
  #mount ActionCable.server => '/cable'
end

app/models/xml.rb
class Xml
  include Mongoid::Document
  include Mongoid::Timestamps
  field :title, type: String
  field :data, type: String
end

app/controllers/xmls_controller.rb
class XmlsController < ApplicationController
  before_action :set_xml, only: [:show, :edit, :update, :destroy]

  # GET /xmls
  # GET /xmls.json
  def index
    @articles = Xml.all.page(params[:page]).per(8)
  end

  # GET /xmls/1
  # GET /xmls/1.json
  def show
    render :xml => @xml.data
  end

  # GET /xmls/new
  def new
    @xml = Xml.new
  end

  # GET /xmls/1/edit
  def edit
  end

  # POST /xmls
  # POST /xmls.json
  def create
    #@xml = Xml.new(xml_params)
    @xml = Xml.new(:data=>request.body.read)

    # respond_to do |format|
      if @xml.save
    #     format.html { redirect_to @xml, notice: 'Xml was successfully created.' }
    #     format.json { render :show, status: :created, location: @xml }
        render :xml => @xml.data
       else
    #     format.html { render :new }
        format.json { render json: @xml.errors, status: :unprocessable_entity }
        end
    # end
  end

  # PATCH/PUT /xmls/1
  # PATCH/PUT /xmls/1.json
  def update
    respond_to do |format|
      if @xml.update(xml_params)
        format.html { redirect_to @xml, notice: 'Xml was successfully updated.' }
        format.json { render :show, status: :ok, location: @xml }
      else
        format.html { render :edit }
        format.json { render json: @xml.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /xmls/1
  # DELETE /xmls/1.json
  def destroy
    @xml.destroy
    respond_to do |format|
      format.html { redirect_to xmls_url, notice: 'Xml was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_xml
      @xml = Xml.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def xml_params
      params.fetch(:xml, {})
    end
end

app/helpers/xmls_helper.rb
module XmlsHelper
end

app/views/xmls/_form.html.erb
<%= simple_form_for(@xml) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/xmls/edit.html.erb
<h1>Editing Xml</h1>

<%= render 'form', xml: @xml %>

<%= link_to 'Show', @xml %> |
<%= link_to 'Back', xmls_path %>

app/views/xmls/index.html.erb
<!-- <p id="notice"><%= notice %></p>

<h1>Xmls</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%# @xmls.each do |xml| %>
      <tr>
        <td><%#= link_to 'Show', xml %></td>
        <td><%#= link_to 'Edit', edit_xml_path(xml) %></td>
        <td><%#= link_to 'Destroy', xml, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <%# end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Xml', new_xml_path %>
 -->



<!-- <p id="notice"><%#= notice %></p> -->

<h1>CDEE DATA <%= link_to 'Back', admin_articles_path, class: "btn btn-success pull-right" %></h1>
<%arr = []
i=0
@articles.each do |article|
  arr[i]=i
  i=i+1
end
#arr.delete(i-1)
%>

<%for i in  arr do %>

<div class="row">
  <div class="col-sm-4" style="background-color: #4ad4ad; border-color: #333;height: 20rem;width: 40rem;">
    <div class="card">
      <div class="card-block">
        <h3 class="card-title"><%= @articles[i].title %></h3>
        <p class="card-text"><%= @articles[i].data.to_s[0...200] %></p>
        <div style="display:inline !important;"><%= link_to 'Show', xml_path(@articles[i]), class: "btn btn-info pull-left" ,:style=> 'display:inline !important; margin-bottom:1000;'%>
        <%= link_to 'Destroy', xml_path(@articles[i]), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger pull-right" ,:style=> 'display:inline !important;'%></div>
      </div>
    </div>
  </div>
  <%i=i+1%>
  <%if @articles[i]!=nil%>
  <div class="col-sm-4 col-sm-offset-1" style="background-color: #4ad4ad; border-color: #333;height: 20rem;width: 40rem;">
    <div class="card">
      <div class="card-block">
        <h3 class="card-title"><%= @articles[i].title %></h3>
        <p class="card-text"><%= @articles[i].data.to_s[0...200] %></p>
        <div style="display:inline !important;"><%= link_to 'Show', xml_path(@articles[i]), class: "btn btn-info pull-left",:style=> 'display:inline !important;' %>
        <%= link_to 'Destroy', xml_path(@articles[i]), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger pull-right" ,:style=> 'display:inline !important;'%></div>
      </div>
    </div>
  </div>
</div>
<% end %>
<br>
<%arr.delete(i)%>
<% end %>

<br>

<span class="pull-right"><%= paginate @articles %></span>

app/views/xmls/new.html.erb
<h1>New Xml</h1>

<%= render 'form', xml: @xml %>

<%= link_to 'Back', xmls_path %>

app/views/xmls/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_xml_path(@xml) %> |
<%= link_to 'Back', xmls_path %>